const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Aluno",
            "description": "Endpoints"
        },
        {
            "name": "Professor",
            "description": "Endpoints"
        },
        {
            "name": "Aula",
            "description": "Endpoints"
        },
        {
            "name": "Dashboard",
            "description": "Endpoints"
        }

    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
    },
    definitions: {
        Professor: {
            nome : "batata",
            email : "batata@email.com",
            senha : "123456",
            telefone : "999999999",
            cpf : "12345678915",
            ultimo_login : "2020-12-10T00:14:09+00:00",
            endereco : "Rua",
            cidade : "BH",
            preco_hora_aula : "",
            descricao : "",
            horarios_disponiveis : "",
            estado_federativo : "Minas Gerais"
        },
        Aluno: {
            nome : "batata",
            email : "batata@email.com",
            senha : "123456",
            telefone : "999999999",
            escola : "Santa Maria",
            cpf : "12345678915",
            ultimo_login : "2020-12-10T00:14:09+00:00",
            endereco : "Rua",
            cidade : "BH",
            ano : "Nono ano",
            estado_federativo : "Minas Gerais"
        },
        Aula: {
            nota_professor : "5",
            nota_aluno : "5",
            confirmacao_aluno : "false",
            confirmacao_professor : "false",
            feedback_aluno : "ok",
            feedback_profesor : "ok",
            materia_aula : "Biologia",
            dia_hora_aula : "2003-04-12 04:05:06",
            cidade : "BH",
            endereco : "Rua",
            estado_federativo : "Minas Gerais",
            id_aluno : "12345678912",
            id_professor : "12345678912"
        }
    }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./server.js')           // Your project's root file
})